// Generated by CoffeeScript 1.9.3
(function() {
  var JiraClient, jira, util;

  util = require('util');

  JiraClient = require('jira-connector');

  jira = new JiraClient({
    host: 'hakkasan.atlassian.net',
    basic_auth: {
      username: 'mechajira',
      password: 'iryu1999!'
    }
  });

  jira.issue.getIssue({
    issueKey: 'WET-18'
  }, function(error, issue) {
    console.log(issue.fields.summary);
  });

  jira.search.search({
    jql: 'comment ~ ghost'
  }, function(error, response) {
    console.log('Issues count: ' + util.inspect(response.issues.length));
    response.issues.forEach(function(issue) {
      console.log('Issue ID: ' + util.inspect(issue.id));
      console.log('Issue key: ' + util.inspect(issue.key));
      console.log('Status: ' + issue.fields.status.name);
      jira.issue.getComments({
        issueKey: issue.key
      }, function(error, response) {
        console.log('Comment count: ', util.inspect(response.comments.length));
        response.comments.forEach(function(comment) {
          console.log('Comment ID: ' + util.inspect(comment.id));
          console.log('Comment: ' + util.inspect(comment.body));
        });
      });
    });
  });

}).call(this);
