project: WDEV
epic: WDEV-4156
issuetype: Task
summary: Basic Social QA
description: Please QA (1) meta title/description, (2) facebook og tags, and (3) twitter card for
assignee:
sites:
 - 1OakLasVegas.com
 - AlibiLoungeLV.com
 - BarePoolLV.com
 - CitizensLasVegas.com
 - FixLasVegas.com
 - HKKHospitality.com
 - HKKLondon.com
 - Hakkasan.com
 - HakkasanGroup.com
 - HakkasanLV.com
 - HerringboneEats.com
 - IvoryOnSunset.com
 - JewelNightclub.com
 - Kumilasvegas.com
 - LilyLasVegas.com
 - Liquidpoollv.com
 - Omniabali.com
 - Omnialv.com
 - Omnianightclub.com
 - Omniasd.com
 - Omnialoscabos.com
 - Redsquarelasvegas.com
 - Sakenohana.com
 - Searsucker.com
 - Stacklasvegas.com
 - Wetrepublic.com
 - Yauatcha.com
 - Yellowtaillasvegas.com
